/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */
package com.baidu.yun.core.json;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int TRUE = 5;
    /** RegularExpression Id. */
    int FALSE = 6;
    /** RegularExpression Id. */
    int NULL = 7;
    /** RegularExpression Id. */
    int INTEGER_LITERAL = 8;
    /** RegularExpression Id. */
    int DECIMAL_LITERAL = 9;
    /** RegularExpression Id. */
    int HEX_LITERAL = 10;
    /** RegularExpression Id. */
    int OCTAL_LITERAL = 11;
    /** RegularExpression Id. */
    int FLOATING_POINT_LITERAL = 12;
    /** RegularExpression Id. */
    int EXPONENT = 13;
    /** RegularExpression Id. */
    int STRING_LITERAL = 14;
    /** RegularExpression Id. */
    int ID = 15;
    /** RegularExpression Id. */
    int LETTER = 16;
    /** RegularExpression Id. */
    int DIGIT = 17;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"",
            "\"true\"", "\"false\"", "\"null\"", "<INTEGER_LITERAL>",
            "<DECIMAL_LITERAL>", "<HEX_LITERAL>", "<OCTAL_LITERAL>",
            "<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<STRING_LITERAL>",
            "<ID>", "<LETTER>", "<DIGIT>", "\"{\"", "\":\"", "\",\"", "\"}\"",
            "\"[\"", "\"]\"", };

}
